### ISSUE TITLE
beamerNotes are repeated if there are not enough pages to fill 

### ISSUE THREAD

**Issue by TeXhackse** [gdiepen/latexbeamer-handoutWithNotes#10]
Issue reported at https://gitlab.ti.bfh.ch/bfh-latex/bfh-ci/-/issues/124

I will add a mechanism to cleanup the boxes when creating a new physical page.

**Comment by samcarter** [comment]
As a temporary workaround until your new mechanism is in place, they could use beamer's lined notes:

```
\documentclass{beamer}

\usepackage{pgfpages}
\pgfpagesuselayout{6 on 1}
\setbeameroption{show notes} 

\setbeamertemplate{note page}[lined]

\makeatletter 
\def\beamer@framenotesbegin{%	at beginning of slide 	
	\gdef\beamer@noteitems{}% 	
	\gdef\beamer@notes{{}}%	used to be totally	empty. 
}
\makeatother

\begin{document}
	
\begin{frame}
	abc
\end{frame}	

\begin{frame}
	abc
\end{frame}	
	
\end{document}
```

**Comment by TeXhackse** [comment]
Oh that was fast. I wanted to resolve it today anyway but thanks :)

**Comment by samcarter** [comment]
oh, bug fixing on the same day! Speedy delivery :)

**Comment by TeXhackse** [comment]
I am trying my best … 

btw your workaround does not help. This issue only appears if one is using the beamerNotes. Therefore it's my patch I have to have another look at.
