### ISSUE TITLE
.sty file missing

### ISSUE THREAD

**Issue by miriquidi7** [gdiepen/latexbeamer-handoutWithNotes#14]
Hi, where do I find the .sty file for the package? Loading the package with \usepackage{handoutWithNotes} just got me the error message that the .sty could not be found.

Best

**Comment by TeXhackse** [comment]
The package is part of tex live. You should be able to install it with that. 

For a local installation without using a TeX distribution we prepared a l3build script. You can run `l3build install` in the root directory of this repo this will install it to your user directory. 

This package is bundled to a dtx file which includes the package and the sty file itself. By running `latex handoutWithNotes.ins` the style file will be generated.  (or pdflatex or lualatex)

**Comment by TeXhackse** [comment]
@miriquidi7 did you manage to get that working? If yes, please close the issue.
