### ISSUE TITLE
undefined control sequence and begin document

### ISSUE THREAD

**Issue by theostewart** [gdiepen/latexbeamer-handoutWithNotes#3]
Hi ...  Thanks for a great package.  I have just updated to the version from Sept 2018, and found an issue which is sort of irritating rather than critical.  I can a sequence of warning messages which read:

l.56 \begin{document}
                     
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Illegal unit of measure (pt inserted).
<to be read again> 

I'm attaching the full log file.  The document typesets, but no lines appear in the notes section

Thanks
Theo Stewart (theodor.stewart@uct.ac.za)
[ORSSA19notes.log](https://github.com/gdiepen/latexbeamer-handoutWithNotes/files/3533779/ORSSA19notes.log)

**Comment by Chris00** [comment]
This is fixed in [my fork](https://github.com/Chris00/latexbeamer-handoutWithNotes).

**Comment by theostewart** [comment]
Hi.   Thanks very much.  That’s great!

Greetings

Theo Stewart
Emeritus Professor and Senior Research Scholar
Department of Statistical Sciences, University of Cape Town

Editor-in-Chief, Journal of Multi-Criteria Decision Analysis (https://onlinelibrary.wiley.com/journal/10991360)

Phone:  (O)  +27-21-6503224
                (M) +27-82-7862216
http://www.stats.uct.ac.za/theodor-stewart-0<http://www.stats.uct.ac.za/theodor-stewart-0>

**Comment by folofjc** [comment]
> This is fixed in [my fork](https://github.com/Chris00/latexbeamer-handoutWithNotes).

Thanks! I had the same problem.

**Comment by TeXhackse** [comment]
it's resolved with todays preparation for CTAN
