### ISSUE TITLE
\pageheight returns error on compilation

### ISSUE THREAD

**Issue by bdeloynes** [gdiepen/latexbeamer-handoutWithNotes#4]
For some reason, I got an `! Undefined sequence` error on compilation (Ubuntu 18.04 with texlive-full installed) returned on compilation by `\pageheight`.

The solution : replace `\pageheight` with `\paperheight` in `handoutWithNotes.sty`.

Not sure if this is ideal, I followed the discussion here : https://tex.stackexchange.com/questions/61469/pageheight-just-inside-layout-package

**Comment by Chris00** [comment]
Workaround 
```latex
\mode<handout>{%
  \newlength{\pageheight}% for “handoutWithNotes”
  \setlength{\pageheight}{\paperheight}
}
```

**Comment by TeXhackse** [comment]
it's resolved with todays preparation for CTAN
