### ISSUE TITLE
"2 on 1 with notes" does not work well in a 16:9 aspect ratio

### ISSUE THREAD

**Issue by Eusebius** [gdiepen/latexbeamer-handoutWithNotes#8]
`\pgfpagesuselayout{2 on 1}` shrinks the slides properly so they fit within page margins, but `\pgfpagesuselayout{1 on 1 with notes}` makes them overflow.

Edit: sorry about the typo in the issue name, it's actually `1 on 1 with notes`.

**Comment by TeXhackse** [comment]
The scaling is identical. The notesbox just don't has any margin. 

I just tried to reconstruct the issue but I am quite sure this is just a missunderstanding. 
Adding and option like `border shrink=5mm` would help to find out.

**Comment by TeXhackse** [comment]
i will close this because I don't get the problem. it's working fine as long as I can see with the current setup.
